package com.google.vr.cardboard;

import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

public class Strings
{
  public static final String CANCEL_BUTTON = "CANCEL_BUTTON";
  public static final String DIALOG_MESSAGE_NO_CARDBOARD = "DIALOG_MESSAGE_NO_CARDBOARD";
  public static final String DIALOG_MESSAGE_SETUP = "DIALOG_MESSAGE_SETUP";
  public static final String DIALOG_TITLE = "DIALOG_TITLE";
  public static final String GO_TO_PLAYSTORE_BUTTON = "GO_TO_PLAYSTORE_BUTTON";
  private static final Map<String, Map<String, String>> LANGUAGE_MAP = new HashMap();
  public static final String NO_BROWSER_TEXT = "NO_BROWSER_TEXT";
  public static final String SETUP_BUTTON = "SETUP_BUTTON";
  
  static
  {
    HashMap localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Δεν βρέθηκε εφ. περιήγ. για άνοιγμα του ιστότοπου");
    localHashMap.put("DIALOG_TITLE", "Διαμόρφωση");
    localHashMap.put("CANCEL_BUTTON", "Ακύρωση");
    localHashMap.put("SETUP_BUTTON", "Ρύθμιση");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Αποκτήστε την εφαρμογή Cardboard για να διαμορφώσετε το σύστημα προβολής σας.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Ρυθμίστε το σύστημα προβολής σας για τη βέλτιστη εμπειρία.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Μετάβαση στο Play Store");
    LANGUAGE_MAP.put("el", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "沒有可開啟網站的瀏覽器");
    localHashMap.put("DIALOG_TITLE", "設定");
    localHashMap.put("CANCEL_BUTTON", "取消");
    localHashMap.put("SETUP_BUTTON", "設定");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "取得 Cardboard 應用程式，以便設定您的檢視器。");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "調整您的檢視器設定以取得最佳使用體驗。");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "前往 Play 商店");
    LANGUAGE_MAP.put("zh_HK", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No browser to open website.");
    localHashMap.put("DIALOG_TITLE", "Configure");
    localHashMap.put("CANCEL_BUTTON", "Cancel");
    localHashMap.put("SETUP_BUTTON", "Setup");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Get the Cardboard app in order to configure your viewer.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Set up your viewer for the best experience.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Go to Play Store");
    LANGUAGE_MAP.put("en", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Không có trình duyệt nào để mở trang web");
    localHashMap.put("DIALOG_TITLE", "Định cấu hình");
    localHashMap.put("CANCEL_BUTTON", "Hủy");
    localHashMap.put("SETUP_BUTTON", "Thiết lập");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Hãy tải ứng dụng Cardboard để định cấu hình thiết bị xem của bạn.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Thiết lập thiết bị xem của bạn để có trải nghiệm tốt nhất.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Truy cập Cửa hàng Play");
    LANGUAGE_MAP.put("vi", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No hi ha cap navegador per obrir el lloc web");
    localHashMap.put("DIALOG_TITLE", "Configura");
    localHashMap.put("CANCEL_BUTTON", "Cancel·la");
    localHashMap.put("SETUP_BUTTON", "Configura");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Per poder configurar el visor, baixa l'aplicació Cardboard.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configura el visor per treure el màxim profit de Cardboard.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Vés a Play Store");
    LANGUAGE_MAP.put("ca", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nessun browser per l'apertura del sito web");
    localHashMap.put("DIALOG_TITLE", "Configura");
    localHashMap.put("CANCEL_BUTTON", "Annulla");
    localHashMap.put("SETUP_BUTTON", "Imposta");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Scarica l'app Cardboard per configurare il tuo visore.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Imposta il visore per un'esperienza ottimale.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Visita il Play Store");
    LANGUAGE_MAP.put("it", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "אין דפדפן שיכול לפתוח את האתר");
    localHashMap.put("DIALOG_TITLE", "הגדרה");
    localHashMap.put("CANCEL_BUTTON", "ביטול");
    localHashMap.put("SETUP_BUTTON", "הגדר");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "‏הורד את אפליקציית Cardboard כדי להגדיר את המציג.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "הגדר את המציג לקבלת החוויה הטובה ביותר.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "‏עבור לחנות Play");
    LANGUAGE_MAP.put("iw", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "لا يتوفَّر متصفِّح لفتح الموقع الإلكتروني");
    localHashMap.put("DIALOG_TITLE", "التهيئة");
    localHashMap.put("CANCEL_BUTTON", "إلغاء");
    localHashMap.put("SETUP_BUTTON", "الإعداد");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "‏الحصول على تطبيق Cardboard لتهيئة العارض.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "إعداد العارض للتمتّع بأفضل تجربة.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "‏الانتقال إلى متجر Play");
    LANGUAGE_MAP.put("ar", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No hay ningún navegador para abrir el sitio web");
    localHashMap.put("DIALOG_TITLE", "Configurar");
    localHashMap.put("CANCEL_BUTTON", "Cancelar");
    localHashMap.put("SETUP_BUTTON", "Configuración");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Obtén la aplicación Cardboard para poder configurar el visor.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configura el visor para obtener la mejor experiencia.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Ir a Play Store");
    LANGUAGE_MAP.put("es_MX", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Chybí prohlížeč k otevření webových stránek");
    localHashMap.put("DIALOG_TITLE", "Konfigurovat");
    localHashMap.put("CANCEL_BUTTON", "Zrušit");
    localHashMap.put("SETUP_BUTTON", "Nastavit");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Stáhněte si aplikaci Cardboard ke konfiguraci svých brýlí.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Nastavte si brýle, aby váš zážitek byl co nejlepší.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Přejít do Obchodu Play");
    LANGUAGE_MAP.put("cs", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Tidak ada browser untuk membuka situs web");
    localHashMap.put("DIALOG_TITLE", "Konfigurasikan");
    localHashMap.put("CANCEL_BUTTON", "Batal");
    localHashMap.put("SETUP_BUTTON", "Penyiapan");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Dapatkan aplikasi Cardboard untuk mengonfigurasikan penampil Anda.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Siapkan penampil Anda untuk pengalaman terbaik.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Buka Play Store");
    LANGUAGE_MAP.put("id", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No tienes navegadores para abrir este sitio web");
    localHashMap.put("DIALOG_TITLE", "Configurar");
    localHashMap.put("CANCEL_BUTTON", "Cancelar");
    localHashMap.put("SETUP_BUTTON", "Configurar visor");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Descárgate la aplicación Cardboard para configurar tu visor.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configura tu visor para aprovechar todas las posibilidades de la realidad virtual.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Ir a Play Store");
    LANGUAGE_MAP.put("es", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Нет браузера для просмотра страницы");
    localHashMap.put("DIALOG_TITLE", "Настройка");
    localHashMap.put("CANCEL_BUTTON", "Отмена");
    localHashMap.put("SETUP_BUTTON", "Настроить");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Чтобы настроить очки, установите приложение Cardboard.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Для наилучших результатов настройте свои очки.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Перейти в Play Маркет");
    LANGUAGE_MAP.put("ru", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Geen browser om website te openen");
    localHashMap.put("DIALOG_TITLE", "Configureren");
    localHashMap.put("CANCEL_BUTTON", "Annuleren");
    localHashMap.put("SETUP_BUTTON", "Instellen");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Download de Cardboard-app om je bril te configureren.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Stel je bril in voor een optimale gebruikerservaring.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Naar de Play Store");
    LANGUAGE_MAP.put("nl", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nenhum navegador encontrado para abrir o site");
    localHashMap.put("DIALOG_TITLE", "Configurar");
    localHashMap.put("CANCEL_BUTTON", "Cancelar");
    localHashMap.put("SETUP_BUTTON", "Configurar");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Faça o download do app do Google Cardboard para configurar seu visualizador.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configure seu visualizador para ter a melhor experiência.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Acessar a Google Play Store");
    LANGUAGE_MAP.put("pt", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Finner ingen nettleser som kan åpne nettstedet");
    localHashMap.put("DIALOG_TITLE", "Konfigurer");
    localHashMap.put("CANCEL_BUTTON", "Avbryt");
    localHashMap.put("SETUP_BUTTON", "Konfigurer");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Skaff deg Cardboard-appen for å kunne konfigurere fremviseren din.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Konfigurer fremviseren din for en best mulig opplevelse.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Gå til Play-butikken");
    LANGUAGE_MAP.put("nb", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Web sitesini açacak bir tarayıcı yok");
    localHashMap.put("DIALOG_TITLE", "Yapılandırma");
    localHashMap.put("CANCEL_BUTTON", "İptal");
    localHashMap.put("SETUP_BUTTON", "Kurulum");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Gözlüğünüzü yapılandırmak için Cardboard uygulamasını indirin.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Gözlüğünüzü en iyi deneyim için hazırlayın.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Google Play Store'a git");
    LANGUAGE_MAP.put("tr", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No browser to open website");
    localHashMap.put("DIALOG_TITLE", "Configure");
    localHashMap.put("CANCEL_BUTTON", "Cancel");
    localHashMap.put("SETUP_BUTTON", "Setup");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Get the Cardboard app in order to configure your viewer.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Set up your viewer for the best experience.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Go to Play Store");
    LANGUAGE_MAP.put("en_AU", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nav pārlūkprogrammas, lai atvērtu vietni");
    localHashMap.put("DIALOG_TITLE", "Konfigurēšana");
    localHashMap.put("CANCEL_BUTTON", "Atcelt");
    localHashMap.put("SETUP_BUTTON", "Iestatīšana");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Lai konfigurētu savu skatītāju, iegūstiet lietotni Cardboard.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Vislabākajiem rezultātiem iestatiet skatītāju.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Pāriet uz Play veikalu");
    LANGUAGE_MAP.put("lv", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nėra naršyklės svetainei atidaryti");
    localHashMap.put("DIALOG_TITLE", "Konfigūruoti");
    localHashMap.put("CANCEL_BUTTON", "Atšaukti");
    localHashMap.put("SETUP_BUTTON", "Sąranka");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Gaukite „Cardboard“ programą, kad galėtumėte konfigūruoti žiūryklę.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Nustatykite žiūryklę, kad būtų teikiamos geriausios funkcijos.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Eiti į „Google Play“ parduot.");
    LANGUAGE_MAP.put("lt", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "ไม่มีเบราว์เซอร์ที่จะใช้เปิดเว็บไซต์");
    localHashMap.put("DIALOG_TITLE", "กำหนดค่า");
    localHashMap.put("CANCEL_BUTTON", "ยกเลิก");
    localHashMap.put("SETUP_BUTTON", "ตั้งค่า");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "ดาวน์โหลดแอป Cardboard เพื่อกำหนดค่ากล่อง");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "ตั้งค่ากล่องเพื่อรับประสบการณ์ที่ดีที่สุด");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "ไปที่ Play สโตร์");
    LANGUAGE_MAP.put("th", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "沒有可開啟網站的瀏覽器");
    localHashMap.put("DIALOG_TITLE", "設定");
    localHashMap.put("CANCEL_BUTTON", "取消");
    localHashMap.put("SETUP_BUTTON", "設定");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "取得 Cardboard 應用程式，以便設定您的檢視器。");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "調整您的檢視器設定以取得最佳使用體驗。");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "前往 Play 商店");
    LANGUAGE_MAP.put("zh_TW", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Niciun browser pentru a deschide site-ul");
    localHashMap.put("DIALOG_TITLE", "Configurați");
    localHashMap.put("CANCEL_BUTTON", "Anulați");
    localHashMap.put("SETUP_BUTTON", "Configurați");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Descărcați aplicația Cardboard pentru a vă configura vizualizatorul.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configurați-vă vizualizatorul pentru o utilizare optimă.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Accesați Magazin Play");
    LANGUAGE_MAP.put("ro", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Sem navegador para abrir o Website");
    localHashMap.put("DIALOG_TITLE", "Configurar");
    localHashMap.put("CANCEL_BUTTON", "Cancelar");
    localHashMap.put("SETUP_BUTTON", "Configurar");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Obtenha a aplicação Cardboard para configurar o seu visualizador.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configure o seu visualizador para obter a melhor experiência.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Ir para a Play Store");
    LANGUAGE_MAP.put("pt_PT", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Walang browser upang buksan ang website");
    localHashMap.put("DIALOG_TITLE", "I-configure");
    localHashMap.put("CANCEL_BUTTON", "Kanselahin");
    localHashMap.put("SETUP_BUTTON", "I-setup");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Kunin ang Cardboard app upang i-configure ang iyong viewer.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "I-set up ang iyong viewer para sa pinakamagandang karanasan.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Pumunta sa Play Store");
    LANGUAGE_MAP.put("fil", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Pas de navigateur pour ouvrir le site Web.");
    localHashMap.put("DIALOG_TITLE", "Configurer");
    localHashMap.put("CANCEL_BUTTON", "Annuler");
    localHashMap.put("SETUP_BUTTON", "Configurer");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Téléchargez l'application Cardboard afin de configurer votre visionneuse.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Pour profiter pleinement de l'application, configurez votre visionneuse.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Accéder à Play Store");
    LANGUAGE_MAP.put("fr", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Няма браузър за отваряне на уебсайта");
    localHashMap.put("DIALOG_TITLE", "Конфигуриране");
    localHashMap.put("CANCEL_BUTTON", "Отказ");
    localHashMap.put("SETUP_BUTTON", "Настройване");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Изтеглете приложението Cardboard, за да конфигурирате очилата си.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "За най-добра работа настройте очилата си.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Към Google Play Магазин");
    LANGUAGE_MAP.put("bg", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nenhum navegador encontrado para abrir o site");
    localHashMap.put("DIALOG_TITLE", "Configurar");
    localHashMap.put("CANCEL_BUTTON", "Cancelar");
    localHashMap.put("SETUP_BUTTON", "Configurar");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Faça o download do app do Google Cardboard para configurar seu visualizador.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configure seu visualizador para ter a melhor experiência.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Acessar a Google Play Store");
    LANGUAGE_MAP.put("pt_BR", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nema preglednika za otvaranje web-lokacije");
    localHashMap.put("DIALOG_TITLE", "Konfiguriraj");
    localHashMap.put("CANCEL_BUTTON", "Odustani");
    localHashMap.put("SETUP_BUTTON", "Postavljanje");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Nabavite aplikaciju Cardboard da biste konfigurirali masku za virtualnu stvarnost.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Postavite masku za virtualnu stvarnost da biste u potpunosti iskoristili sve značajke.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Idi na Trgovinu Play");
    LANGUAGE_MAP.put("hr", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No hay ningún navegador para abrir el sitio web");
    localHashMap.put("DIALOG_TITLE", "Configurar");
    localHashMap.put("CANCEL_BUTTON", "Cancelar");
    localHashMap.put("SETUP_BUTTON", "Configuración");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Obtén la aplicación Cardboard para poder configurar el visor.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Configura el visor para obtener la mejor experiencia.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Ir a Play Store");
    LANGUAGE_MAP.put("es_US", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Kein Browser zum Öffnen der Website gefunden");
    localHashMap.put("DIALOG_TITLE", "Konfigurieren");
    localHashMap.put("CANCEL_BUTTON", "Abbrechen");
    localHashMap.put("SETUP_BUTTON", "Einrichtung");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Holen Sie sich die Cardboard App zum Konfigurieren Ihrer VR-Brille.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Richten Sie Ihre VR-Brille für optimale Virtual-Reality-Erlebnisse ein.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Zum Play Store");
    LANGUAGE_MAP.put("de", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Nem található böngésző a webhely megnyitásához");
    localHashMap.put("DIALOG_TITLE", "Konfigurálás");
    localHashMap.put("CANCEL_BUTTON", "Mégse");
    localHashMap.put("SETUP_BUTTON", "Beállítás");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Szemüvege konfigurálásához töltse le a Cardboard alkalmazást.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "A szemüveg beállítása a legjobb élmény eléréséhez.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Play Áruház megnyitása");
    LANGUAGE_MAP.put("hu", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "مرورگری برای باز کردن وب‌سایت نیست");
    localHashMap.put("DIALOG_TITLE", "پیکربندی");
    localHashMap.put("CANCEL_BUTTON", "لغو");
    localHashMap.put("SETUP_BUTTON", "راه‌اندازی");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "‏برای پیکربندی نظاره‌گر، برنامه Cardboard را دریافت کنید.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "برای اینکه بهترین تجربه را داشته باشید، نظاره‌گرتان را راه‌اندازی کنید.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "‏برو به فروشگاه Play");
    LANGUAGE_MAP.put("fa", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "वेबसाइट खोलने के लिए कोई ब्राउज़र नहीं");
    localHashMap.put("DIALOG_TITLE", "कॉन्फ़िगर करें");
    localHashMap.put("CANCEL_BUTTON", "रोकें");
    localHashMap.put("SETUP_BUTTON", "सेटअप");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "अपना व्यूअर कॉन्फ़िगर करने के लिए कार्डबोर्ड ऐप्लिकेशन प्राप्त करें.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "श्रेष्ठ अनुभव के लिए अपना व्यूअर सेट करें.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Play स्‍टोर पर जाएं");
    LANGUAGE_MAP.put("hi", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Ei verkkosivuston avaamiseen sopivaa selainta");
    localHashMap.put("DIALOG_TITLE", "Määritä");
    localHashMap.put("CANCEL_BUTTON", "Peruuta");
    localHashMap.put("SETUP_BUTTON", "Aloita määritys");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Lataa Cardboard-sovellus lasien asetusten määrittämistä varten.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Määritä lasien asetukset, jotta katselukokemus on mahdollisimman miellyttävä.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Siirry Play Kauppaan");
    LANGUAGE_MAP.put("fi", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Der er ingen browser til at åbne websitet");
    localHashMap.put("DIALOG_TITLE", "Konfigurer");
    localHashMap.put("CANCEL_BUTTON", "Annuller");
    localHashMap.put("SETUP_BUTTON", "Konfigurer");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Få Cardboard-appen, så du kan konfigurere fremviseren.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Konfigurer din fremviser for at få den bedste oplevelse.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Gå til Play Butik");
    LANGUAGE_MAP.put("da", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No browser to open website");
    localHashMap.put("DIALOG_TITLE", "Configure");
    localHashMap.put("CANCEL_BUTTON", "Cancel");
    localHashMap.put("SETUP_BUTTON", "Setup");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Get the Cardboard app in order to configure your viewer.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Set up your viewer for the best experience.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Go to Play Store");
    LANGUAGE_MAP.put("en_IN", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "ウェブサイトを開くブラウザがありません");
    localHashMap.put("DIALOG_TITLE", "設定");
    localHashMap.put("CANCEL_BUTTON", "キャンセル");
    localHashMap.put("SETUP_BUTTON", "セットアップ");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "ビューアを設定するには、Cardboardアプリを入手してください。");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "快適にご利用いただくために、ビューアをセットアップしてください。");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Google Playストアへ");
    LANGUAGE_MAP.put("ja", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "אין דפדפן שיכול לפתוח את האתר");
    localHashMap.put("DIALOG_TITLE", "הגדרה");
    localHashMap.put("CANCEL_BUTTON", "ביטול");
    localHashMap.put("SETUP_BUTTON", "הגדר");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "‏הורד את אפליקציית Cardboard כדי להגדיר את המציג.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "הגדר את המציג לקבלת החוויה הטובה ביותר.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "‏עבור לחנות Play");
    LANGUAGE_MAP.put("he", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "找不到可以打开网站的浏览器");
    localHashMap.put("DIALOG_TITLE", "配置");
    localHashMap.put("CANCEL_BUTTON", "取消");
    localHashMap.put("SETUP_BUTTON", "设置");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "获取 Cardboard 应用以配置您的眼镜。");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "设置眼镜以获得最佳体验。");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "转到 Play 商店");
    LANGUAGE_MAP.put("zh_CN", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Нема прегледача за отварање веб-сајта");
    localHashMap.put("DIALOG_TITLE", "Конфигуришите");
    localHashMap.put("CANCEL_BUTTON", "Откажи");
    localHashMap.put("SETUP_BUTTON", "Подешавање");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Преузмите апликацију Cardboard да бисте конфигурисали маску.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Подесите маску за најбољи доживљај.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Иди у Play продавницу");
    LANGUAGE_MAP.put("sr", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "웹사이트를 열 브라우저가 없습니다.");
    localHashMap.put("DIALOG_TITLE", "설정");
    localHashMap.put("CANCEL_BUTTON", "취소");
    localHashMap.put("SETUP_BUTTON", "설정");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "뷰어를 설정하려면 Cardboard 앱을 받으세요.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "최적의 경험을 위해 뷰어를 설정하세요.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Play 스토어로 이동");
    LANGUAGE_MAP.put("ko", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Ingen webbläsare kan öppna webbsidan");
    localHashMap.put("DIALOG_TITLE", "Konfigurera");
    localHashMap.put("CANCEL_BUTTON", "Avbryt");
    localHashMap.put("SETUP_BUTTON", "Konfiguration");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Ladda ned Cardboard-appen om du vill konfigurera visaren.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Konfigurera visaren för bästa upplevelse.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Öppna Play Butik");
    LANGUAGE_MAP.put("sv", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Žiaden prehliadač na otvorenie webu");
    localHashMap.put("DIALOG_TITLE", "Konfigurácia");
    localHashMap.put("CANCEL_BUTTON", "Zrušiť");
    localHashMap.put("SETUP_BUTTON", "Nastaviť");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Získajte aplikáciu Cardboard, aby ste mohli konfigurovať zobrazovač.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Nastavte si zobrazovač a dosiahnite tie najlepšie výsledky.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Prejsť do služby Obchod Play");
    LANGUAGE_MAP.put("sk", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Brak przeglądarki, w której można otworzyć witrynę");
    localHashMap.put("DIALOG_TITLE", "Konfiguruj");
    localHashMap.put("CANCEL_BUTTON", "Anuluj");
    localHashMap.put("SETUP_BUTTON", "Konfiguracja");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Pobierz aplikację Cardboard, aby ustawić gogle.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Ustaw gogle, aby uzyskać optymalny efekt.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Otwórz Sklep Play");
    LANGUAGE_MAP.put("pl", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "No browser to open website");
    localHashMap.put("DIALOG_TITLE", "Configure");
    localHashMap.put("CANCEL_BUTTON", "Cancel");
    localHashMap.put("SETUP_BUTTON", "Setup");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Get the Cardboard app in order to configure your viewer.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Set up your viewer for the best experience.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Go to Play Store");
    LANGUAGE_MAP.put("en_GB", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Немає веб-переглядача для сайту");
    localHashMap.put("DIALOG_TITLE", "Налаштувати");
    localHashMap.put("CANCEL_BUTTON", "Скасувати");
    localHashMap.put("SETUP_BUTTON", "Налаштування");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Завантажте додаток Cardboard, щоб налаштувати окуляри.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Налаштуйте окуляри й отримайте найкращі враження.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "Перейти в Google Play");
    LANGUAGE_MAP.put("uk", localHashMap);
    localHashMap = new HashMap();
    localHashMap.put("NO_BROWSER_TEXT", "Tega mesta ni mogoče odpreti z nobenim brskalnikom");
    localHashMap.put("DIALOG_TITLE", "Konfiguriranje");
    localHashMap.put("CANCEL_BUTTON", "Prekliči");
    localHashMap.put("SETUP_BUTTON", "Namesti");
    localHashMap.put("DIALOG_MESSAGE_NO_CARDBOARD", "Če želite konfigurirati pregledovalnik, namestite aplikacijo Cardboard.");
    localHashMap.put("DIALOG_MESSAGE_SETUP", "Da bo izkušnja čim boljša, namestite pregledovalnik.");
    localHashMap.put("GO_TO_PLAYSTORE_BUTTON", "V Google Play");
    LANGUAGE_MAP.put("sl", localHashMap);
  }
  
  private static Map<String, String> getLanguageMap(Locale paramLocale)
  {
    paramLocale = paramLocale.getLanguage();
    if (LANGUAGE_MAP.containsKey(paramLocale)) {
      return (Map)LANGUAGE_MAP.get(paramLocale);
    }
    return (Map)LANGUAGE_MAP.get("en");
  }
  
  public static String getString(String paramString)
  {
    return getString(paramString, Locale.getDefault());
  }
  
  private static String getString(String paramString, Locale paramLocale)
  {
    paramLocale = getLanguageMap(paramLocale);
    if (paramLocale.containsKey(paramString)) {
      return (String)paramLocale.get(paramString);
    }
    return (String)((Map)LANGUAGE_MAP.get("en")).get(paramString);
  }
}

/* Location:
 * Qualified Name:     com.google.vr.cardboard.Strings
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */