package com.google.android.gms.internal;

import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import java.util.concurrent.TimeUnit;

public final class zzln<R extends Result>
  extends OptionalPendingResult<R>
{
  private final zzlc<R> zzacI;
  
  public zzln(PendingResult<R> paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzlc)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    zzacI = ((zzlc)paramPendingResult);
  }
  
  public R await()
  {
    return zzacI.await();
  }
  
  public R await(long paramLong, TimeUnit paramTimeUnit)
  {
    return zzacI.await(paramLong, paramTimeUnit);
  }
  
  public void cancel()
  {
    zzacI.cancel();
  }
  
  public R get()
  {
    if (isDone()) {
      return await(0L, TimeUnit.MILLISECONDS);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public boolean isCanceled()
  {
    return zzacI.isCanceled();
  }
  
  public boolean isDone()
  {
    return zzacI.isReady();
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback)
  {
    zzacI.setResultCallback(paramResultCallback);
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    zzacI.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  public void zza(PendingResult.zza paramzza)
  {
    zzacI.zza(paramzza);
  }
  
  public Integer zznF()
  {
    return zzacI.zznF();
  }
}

/* Location:
 * Qualified Name:     com.google.android.gms.internal.zzln
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */